[package]
name = "cargobay-vz"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"

[dependencies]
cargobay-core = { path = "../cargobay-core" }
tracing = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
dispatch2 = "0.3"
objc2 = "0.6"
objc2-foundation = "0.3"
